version: '3.3'
services:
  pg:
    container_name: user-serviceApiDesign_db
    image: postgres
    ports:
      - "5432:5432"  # might change based on production needs
    volumes:
      - db_data:/var/lib/postgresql
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:   # Production database

volumes:
  db_data: {}
